### ISSUE TITLE
最后提交抢购（秒杀）订单的时候，请求body是放的json还是form的格式

### ISSUE THREAD

**Issue by luckybir** [lvgithub/jd_seckill_new#5]

**Comment by lvgithub** [comment]
json

**Comment by luckybir** [comment]
但是 603行：
        resp = self.session.post(
            url=url,
            params=payload,
            data=self.seckill_order_data.get(
                self.sku_id),
            headers=headers)

这里没有看到转成json的格式哦，如果request post json不是要调用 json.dumps来转一下吗

**Comment by github-sxw** [comment]
> 但是 603行：
> resp = self.session.post(
> url=url,
> params=payload,
> data=self.seckill_order_data.get(
> self.sku_id),
> headers=headers)
> 
> 这里没有看到转成json的格式哦，如果request post json不是要调用 json.dumps来转一下吗

mark一下，看看啥情况

**Comment by lvgithub** [comment]
说错了，是"application/x-www-form-urlencoded

**Comment by luckybir** [comment]
solved
